- id: terraform_docs
  name: Terraform docs
  description: Inserts input and output documentation into README.md (using terraform-docs).
  require_serial: true
  always_run: true
  entry: terraform_docs.sh
  language: script
- id: markdownlint
  name: markdownlint
  description: "Checks the style of Markdown/Commonmark files."
  require_serial: true
  always_run: true
  entry: markdownlint.sh
  language: script
- id: check_modules_use_tag
  name: check_modules_use_tag
  description: "Checks that Terragrunt env files point to a tag and not enother form of ref."
  require_serial: true
  always_run: true
  entry: check_modules_use_tag.sh
  language: script
  # files: \(env\|root\)\.ya*ml$
  # files: root.yaml
  files: \(env\|root\)\.yaml$
