- id: check-modules-use-tag
  name: check-modules-use-tag
  entry: hooks/check-modules-use-tag.sh
  description: Checks that Terragrunt env file modules refs point to a tag.
  language: script
  files: (env|root)\.yaml$
- id: add-missing-readme
  name: add-missing-readme
  entry: hooks/add-missing-readme.sh
  description: Makes sure a README.md exists in any directory with a main.tf.
  language: script
  files: (main\.tf)$
  exclude: \.terraform\/.*$
