- id: markdownlint
  name: markdownlint
  entry: hooks/markdownlint.sh
  description: Checks the style of Markdown files.
  language: script
  files: \.md$
  require_serial: true
  always_run: true
- id: check-modules-use-tag
  name: check-modules-use-tag
  entry: hooks/check-modules-use-tag.sh
  description: Checks that Terragrunt env file modules refs point to a tag.
  language: script
  files: (env|root)\.yaml$
  require_serial: true
  always_run: true
- id: add-missing-readme
  name: add-missing-readme
  entry: hooks/add-missing-readme.sh
  description: Makes sure a README.md exists in any directory with a main.tf.
  language: script
  files: (main\.tf)$
  exclude: \.terraform\/.*$
  require_serial: true
  always_run: true
